blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/washingtonstateuniversity/hrswp-plugin-sqlsrv-db/#readme
    about: Information on installation, updating, and development is found in the Readme.
